package bankManagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;

public class AccountDAO {

    // SAVE ACCOUNT (Account Number generated by DB)
    public void saveAccount(Account acc) throws Exception {

    	String query =
                "INSERT INTO accounts " +
                "(name, dob, age, minor, mobile_number, email, address, aadhaar_number, pan_number, balance, " +
                "account_type, debit_card_number, debit_card_status, card_type, card_feature, " +
                "guardian_name, guardian_mobile, guardian_email, guardian_pan, nominee_name, " +
                "nominee_age, nominee_relationship, nominee_mobile, nominee_pan, username, password)" +
                "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
        try (
        	    Connection con = DBConnection.getConnection();
        	    PreparedStatement ps = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
        	){
        	
                ps.setString(1, acc.getName());
                ps.setDate(2, new java.sql.Date(acc.getDob().getTime()));
                ps.setInt(3, acc.getAge());
                ps.setBoolean(4, acc.isMinor());
                ps.setString(5, acc.getMobileNumber());
                ps.setString(6, acc.getEmail());
                ps.setString(7, acc.getAddress());
                ps.setString(8, acc.getAadhaarNumber());
                ps.setString(9, acc.getPanNumber());
                ps.setDouble(10, acc.getBalanceAmount());
                ps.setString(11, acc.getAccountType());
                ps.setString(12, acc.getDebitCardNumber());
                ps.setString(13, acc.getDebitCardStatus().name());
                ps.setString(14, acc.getCardType());
                ps.setString(15, acc.getCardFeature());
                ps.setString(16, acc.getGuardianName());
                ps.setString(17, acc.getGuardianMobileNumber());
                ps.setString(18, acc.getGuardianEmail());
                ps.setString(19, acc.getGuardianPanNumber());
                ps.setString(20, acc.getNomineeName());
                
                // Nominee age validation
                if (acc.getNomineeAge() != null)
                    ps.setInt(21, acc.getNomineeAge());
                else
                    ps.setNull(21, java.sql.Types.INTEGER);

                ps.setString(22,acc.getNomineeRelationship());
                ps.setString(23, acc.getNomineeMobileNumber());
                ps.setString(24, acc.getNomineePanNumber());
                ps.setString(25, acc.getUsername());
                ps.setString(26, acc.getPassword());

                ps.executeUpdate();

                // Get auto-generated account number
                ResultSet rs = ps.getGeneratedKeys();
                if (rs.next()) {
                    acc.setAccountNumber(rs.getString(1));
                }
                
        }

    }

    // UPDATE ACCOUNT (Profile / Balance / Card changes)
    public void updateAccount(Account acc) throws Exception {

    	String query =
	            "UPDATE accounts SET name=?, address=?, email=?, mobile_number=?, balance=?, debit_card_number=?, " +
	            "debit_card_status=?, card_type=?, card_feature=?, nominee_name=?, nominee_age=?, " +
	            "nominee_mobile=?, nominee_relationship=?, nominee_pan=?, password=? " +
	            "WHERE account_number=?";

    	try (
        	    Connection con = DBConnection.getConnection();
        	    PreparedStatement ps = con.prepareStatement(query);
        	){

    	        ps.setString(1, acc.getName());
    	        ps.setString(2, acc.getAddress());
    	        ps.setString(3, acc.getEmail());
    	        ps.setString(4, acc.getMobileNumber());
    	        ps.setDouble(5, acc.getBalanceAmount());
    	        ps.setString(6, acc.getDebitCardNumber());
    	        ps.setString(7, acc.getDebitCardStatus().name());
    	        ps.setString(8, acc.getCardType());
    	        ps.setString(9, acc.getCardFeature());
    	        ps.setString(10,acc.getNomineeName());
    	        
    	        // Nominee age validation
    	        if (acc.getNomineeAge() != null)
    	            ps.setInt(11, acc.getNomineeAge());
    	        else
    	            ps.setNull(11, java.sql.Types.INTEGER);

    	        ps.setString(12, acc.getNomineeMobileNumber());
    	        ps.setString(13,acc.getNomineeRelationship());
    	        ps.setString(14, acc.getNomineePanNumber());
    	        ps.setString(15, acc.getPassword());
    	        ps.setString(16, acc.getAccountNumber());

    	        ps.executeUpdate();
    	        
    		}
    	
    }

    // LOAD ALL ACCOUNTS INTO HASHMAP
    public HashMap<String, Account> loadAccounts() throws Exception {

        HashMap<String, Account> map = new HashMap<>();

        String query = "SELECT * FROM accounts";

        try (
            Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
        ) {
            while (rs.next()) {
                try {
                    Account acc = new Account();

                    acc.setAccountNumber(rs.getString("account_number"));
                    acc.setName(rs.getString("name"));
                    acc.setDob(rs.getDate("dob"));
                    acc.setAge(rs.getInt("age"));    
                    acc.setMobileNumber(rs.getString("mobile_number"));
                    acc.setEmail(rs.getString("email"));
                    acc.setAddress(rs.getString("address"));
                    acc.setAadhaarNumber(rs.getString("aadhaar_number"));
                    acc.setPanNumber(rs.getString("pan_number"));
                    acc.setBalanceAmount(rs.getDouble("balance"));
                    acc.setAccountType(rs.getString("account_type"));

                    acc.setDebitCardNumber(rs.getString("debit_card_number"));
                    acc.setDebitCardStatus(
                    	    DebitCardStatus.valueOf(rs.getString("debit_card_status"))
                    	);
                    acc.setCardType(rs.getString("card_type"));
                    acc.setCardFeature(rs.getString("card_feature"));

                    acc.setGuardianName(rs.getString("guardian_name"));
                    acc.setGuardianMobileNumber(rs.getString("guardian_mobile"));
                    acc.setGuardianEmail(rs.getString("guardian_email"));
                    acc.setGuardianPanNumber(rs.getString("guardian_pan"));

                    acc.setNomineeName(rs.getString("nominee_name"));

                    // Nominee Age validation
                    int nomineeAge = rs.getInt("nominee_age");
                    if (rs.wasNull())
                        acc.setNomineeAge(null);
                    else
                        acc.setNomineeAge(nomineeAge);

                    acc.setNomineeRelationship(rs.getString("nominee_relationship"));
                    acc.setNomineeMobileNumber(rs.getString("nominee_mobile"));
                    acc.setNomineePanNumber(rs.getString("nominee_pan"));

                    acc.setUsername(rs.getString("username"));
                    acc.setPassword(rs.getString("password"));

                    map.put(acc.getAccountNumber(), acc);

                } catch (Exception e) {
                    System.out.println("Skipping corrupted account record.");
                }
            }
        }

        return map;
    }
    
    // DELETE ACCOUNT (Account Closing)
    public void deleteAccount(String accountNumber) throws Exception {

    	String query = "DELETE FROM accounts WHERE account_number=?";
    	
    	try (
    		    Connection con = DBConnection.getConnection();
    		    PreparedStatement ps = con.prepareStatement(query);
    		) {
    		    ps.setString(1, accountNumber);
    		    ps.executeUpdate();
    		}

    }

}

